TokenInfo(type=63 (ENCODING), string='utf-8', start=(0, 0), end=(0, 0), line='')
TokenInfo(type=1 (NAME), string='include', start=(1, 0), end=(1, 7), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=54 (OP), string='(', start=(1, 8), end=(1, 9), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=1 (NAME), string='core', start=(1, 9), end=(1, 13), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=54 (OP), string='.', start=(1, 13), end=(1, 14), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=1 (NAME), string='stdio', start=(1, 14), end=(1, 19), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=54 (OP), string=')', start=(1, 19), end=(1, 20), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=1 (NAME), string='as', start=(1, 21), end=(1, 23), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=1 (NAME), string='stdio', start=(1, 24), end=(1, 29), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=4 (NEWLINE), string='\r\n', start=(1, 29), end=(1, 31), line='include (core.stdio) as stdio\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(2, 0), end=(2, 2), line='\r\n')
TokenInfo(type=61 (COMMENT), string='# dsfds', start=(3, 0), end=(3, 7), line='# dsfds\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(3, 7), end=(3, 9), line='# dsfds\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(4, 0), end=(4, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='extern', start=(5, 0), end=(5, 6), line='extern {\r\n')
TokenInfo(type=54 (OP), string='{', start=(5, 7), end=(5, 8), line='extern {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(5, 8), end=(5, 10), line='extern {\r\n')
TokenInfo(type=1 (NAME), string='sqrtf', start=(6, 4), end=(6, 9), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=54 (OP), string='(', start=(6, 9), end=(6, 10), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=1 (NAME), string='float', start=(6, 10), end=(6, 15), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=54 (OP), string=',', start=(6, 15), end=(6, 16), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=1 (NAME), string='float', start=(6, 17), end=(6, 22), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=54 (OP), string=')', start=(6, 22), end=(6, 23), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=54 (OP), string='->', start=(6, 24), end=(6, 26), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=1 (NAME), string='float', start=(6, 27), end=(6, 32), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(6, 32), end=(6, 34), line='    sqrtf(float, float) -> float\r\n')
TokenInfo(type=54 (OP), string='}', start=(7, 0), end=(7, 1), line='}\r\n')
TokenInfo(type=4 (NEWLINE), string='\r\n', start=(7, 1), end=(7, 3), line='}\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(8, 0), end=(8, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='something', start=(9, 0), end=(9, 9), line='something {\r\n')
TokenInfo(type=54 (OP), string='{', start=(9, 10), end=(9, 11), line='something {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(9, 11), end=(9, 13), line='something {\r\n')
TokenInfo(type=1 (NAME), string='binarySearch', start=(10, 4), end=(10, 16), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(10, 16), end=(10, 17), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(10, 17), end=(10, 20), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=',', start=(10, 20), end=(10, 21), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='start', start=(10, 22), end=(10, 27), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=',', start=(10, 27), end=(10, 28), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(10, 29), end=(10, 32), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(10, 32), end=(10, 33), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(10, 34), end=(10, 35), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(10, 35), end=(10, 37), line='    binarySearch(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='if', start=(11, 8), end=(11, 10), line='        if start > end {\r\n')
TokenInfo(type=1 (NAME), string='start', start=(11, 11), end=(11, 16), line='        if start > end {\r\n')
TokenInfo(type=54 (OP), string='>', start=(11, 17), end=(11, 18), line='        if start > end {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(11, 19), end=(11, 22), line='        if start > end {\r\n')
TokenInfo(type=54 (OP), string='{', start=(11, 23), end=(11, 24), line='        if start > end {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(11, 24), end=(11, 26), line='        if start > end {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(12, 12), end=(12, 18), line='            return -1\r\n')
TokenInfo(type=54 (OP), string='-', start=(12, 19), end=(12, 20), line='            return -1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(12, 20), end=(12, 21), line='            return -1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(12, 21), end=(12, 23), line='            return -1\r\n')
TokenInfo(type=54 (OP), string='}', start=(13, 8), end=(13, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(13, 9), end=(13, 11), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(14, 0), end=(14, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(15, 8), end=(15, 11), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='=', start=(15, 12), end=(15, 13), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='(', start=(15, 14), end=(15, 15), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=1 (NAME), string='start', start=(15, 15), end=(15, 20), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='+', start=(15, 21), end=(15, 22), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=1 (NAME), string='end', start=(15, 23), end=(15, 26), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string=')', start=(15, 26), end=(15, 27), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='/', start=(15, 28), end=(15, 29), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=2 (NUMBER), string='2', start=(15, 30), end=(15, 31), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(15, 31), end=(15, 33), line='        mid = (start + end) / 2\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(16, 0), end=(16, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='if', start=(17, 8), end=(17, 10), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(17, 11), end=(17, 14), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=54 (OP), string='[', start=(17, 14), end=(17, 15), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(17, 15), end=(17, 18), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=54 (OP), string=']', start=(17, 18), end=(17, 19), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=54 (OP), string='==', start=(17, 20), end=(17, 22), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=2 (NUMBER), string='0', start=(17, 23), end=(17, 24), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=54 (OP), string='{', start=(17, 25), end=(17, 26), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(17, 26), end=(17, 28), line='        if arr[mid] == 0 {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(18, 12), end=(18, 18), line='            return mid\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(18, 19), end=(18, 22), line='            return mid\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(18, 22), end=(18, 24), line='            return mid\r\n')
TokenInfo(type=54 (OP), string='}', start=(19, 8), end=(19, 9), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=1 (NAME), string='elif', start=(19, 10), end=(19, 14), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(19, 15), end=(19, 18), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=54 (OP), string='[', start=(19, 18), end=(19, 19), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(19, 19), end=(19, 22), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=54 (OP), string=']', start=(19, 22), end=(19, 23), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=54 (OP), string='==', start=(19, 24), end=(19, 26), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(19, 27), end=(19, 28), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=54 (OP), string='{', start=(19, 29), end=(19, 30), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(19, 30), end=(19, 32), line='        } elif arr[mid] == 1 {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(20, 12), end=(20, 18), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='binarySearch', start=(20, 19), end=(20, 31), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string='(', start=(20, 31), end=(20, 32), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(20, 32), end=(20, 35), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=',', start=(20, 35), end=(20, 36), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(20, 37), end=(20, 40), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string='+', start=(20, 41), end=(20, 42), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(20, 43), end=(20, 44), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=',', start=(20, 44), end=(20, 45), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='end', start=(20, 46), end=(20, 49), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=')', start=(20, 49), end=(20, 50), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(20, 50), end=(20, 52), line='            return binarySearch(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string='}', start=(21, 8), end=(21, 9), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='else', start=(21, 10), end=(21, 14), line='        } else {\r\n')
TokenInfo(type=54 (OP), string='{', start=(21, 15), end=(21, 16), line='        } else {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(21, 16), end=(21, 18), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(22, 12), end=(22, 18), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=1 (NAME), string='binarySearch', start=(22, 19), end=(22, 31), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string='(', start=(22, 31), end=(22, 32), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(22, 32), end=(22, 35), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string=',', start=(22, 35), end=(22, 36), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=1 (NAME), string='start', start=(22, 37), end=(22, 42), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string=',', start=(22, 42), end=(22, 43), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(22, 44), end=(22, 47), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string='-', start=(22, 48), end=(22, 49), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(22, 50), end=(22, 51), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string=')', start=(22, 51), end=(22, 52), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(22, 52), end=(22, 54), line='            return binarySearch(arr, start, mid - 1)\r\n')
TokenInfo(type=54 (OP), string='}', start=(23, 8), end=(23, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(23, 9), end=(23, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(24, 4), end=(24, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(24, 5), end=(24, 7), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(25, 0), end=(25, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='mergeSort', start=(26, 4), end=(26, 13), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(26, 13), end=(26, 14), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(26, 14), end=(26, 17), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=',', start=(26, 17), end=(26, 18), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='start', start=(26, 19), end=(26, 24), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=',', start=(26, 24), end=(26, 25), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(26, 26), end=(26, 29), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(26, 29), end=(26, 30), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(26, 31), end=(26, 32), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(26, 32), end=(26, 34), line='    mergeSort(arr, start, end) {\r\n')
TokenInfo(type=1 (NAME), string='if', start=(27, 8), end=(27, 10), line='        if start < end {\r\n')
TokenInfo(type=1 (NAME), string='start', start=(27, 11), end=(27, 16), line='        if start < end {\r\n')
TokenInfo(type=54 (OP), string='<', start=(27, 17), end=(27, 18), line='        if start < end {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(27, 19), end=(27, 22), line='        if start < end {\r\n')
TokenInfo(type=54 (OP), string='{', start=(27, 23), end=(27, 24), line='        if start < end {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(27, 24), end=(27, 26), line='        if start < end {\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(28, 12), end=(28, 15), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='=', start=(28, 16), end=(28, 17), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='(', start=(28, 18), end=(28, 19), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=1 (NAME), string='start', start=(28, 19), end=(28, 24), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='+', start=(28, 25), end=(28, 26), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=1 (NAME), string='end', start=(28, 27), end=(28, 30), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string=')', start=(28, 30), end=(28, 31), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=54 (OP), string='/', start=(28, 32), end=(28, 33), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=2 (NUMBER), string='2', start=(28, 34), end=(28, 35), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(28, 35), end=(28, 37), line='            mid = (start + end) / 2\r\n')
TokenInfo(type=1 (NAME), string='mergeSort', start=(29, 12), end=(29, 21), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=54 (OP), string='(', start=(29, 21), end=(29, 22), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(29, 22), end=(29, 25), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=54 (OP), string=',', start=(29, 25), end=(29, 26), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=1 (NAME), string='start', start=(29, 27), end=(29, 32), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=54 (OP), string=',', start=(29, 32), end=(29, 33), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(29, 34), end=(29, 37), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=54 (OP), string=')', start=(29, 37), end=(29, 38), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(29, 38), end=(29, 40), line='            mergeSort(arr, start, mid)\r\n')
TokenInfo(type=1 (NAME), string='mergeSort', start=(30, 12), end=(30, 21), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string='(', start=(30, 21), end=(30, 22), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(30, 22), end=(30, 25), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=',', start=(30, 25), end=(30, 26), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(30, 27), end=(30, 30), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string='+', start=(30, 31), end=(30, 32), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(30, 33), end=(30, 34), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=',', start=(30, 34), end=(30, 35), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=1 (NAME), string='end', start=(30, 36), end=(30, 39), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=54 (OP), string=')', start=(30, 39), end=(30, 40), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(30, 40), end=(30, 42), line='            mergeSort(arr, mid + 1, end)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(31, 12), end=(31, 14), line='            \r\n')
TokenInfo(type=61 (COMMENT), string='# merge(arr, start, mid, end)', start=(32, 12), end=(32, 41), line='            # merge(arr, start, mid, end)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(32, 41), end=(32, 43), line='            # merge(arr, start, mid, end)\r\n')
TokenInfo(type=1 (NAME), string='new_arr', start=(33, 12), end=(33, 19), line='            new_arr = []\r\n')
TokenInfo(type=54 (OP), string='=', start=(33, 20), end=(33, 21), line='            new_arr = []\r\n')
TokenInfo(type=54 (OP), string='[', start=(33, 22), end=(33, 23), line='            new_arr = []\r\n')
TokenInfo(type=54 (OP), string=']', start=(33, 23), end=(33, 24), line='            new_arr = []\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(33, 24), end=(33, 26), line='            new_arr = []\r\n')
TokenInfo(type=1 (NAME), string='i', start=(34, 12), end=(34, 13), line='            i = start\r\n')
TokenInfo(type=54 (OP), string='=', start=(34, 14), end=(34, 15), line='            i = start\r\n')
TokenInfo(type=1 (NAME), string='start', start=(34, 16), end=(34, 21), line='            i = start\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(34, 21), end=(34, 23), line='            i = start\r\n')
TokenInfo(type=1 (NAME), string='j', start=(35, 12), end=(35, 13), line='            j = mid + 1\r\n')
TokenInfo(type=54 (OP), string='=', start=(35, 14), end=(35, 15), line='            j = mid + 1\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(35, 16), end=(35, 19), line='            j = mid + 1\r\n')
TokenInfo(type=54 (OP), string='+', start=(35, 20), end=(35, 21), line='            j = mid + 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(35, 22), end=(35, 23), line='            j = mid + 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(35, 23), end=(35, 25), line='            j = mid + 1\r\n')
TokenInfo(type=1 (NAME), string='while', start=(36, 12), end=(36, 17), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=1 (NAME), string='i', start=(36, 18), end=(36, 19), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=54 (OP), string='<=', start=(36, 20), end=(36, 22), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(36, 23), end=(36, 26), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=54 (OP), string='&', start=(36, 27), end=(36, 28), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=54 (OP), string='&', start=(36, 28), end=(36, 29), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=1 (NAME), string='j', start=(36, 30), end=(36, 31), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=54 (OP), string='<=', start=(36, 32), end=(36, 34), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(36, 35), end=(36, 38), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=54 (OP), string='{', start=(36, 39), end=(36, 40), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(36, 40), end=(36, 42), line='            while i <= mid && j <= end {\r\n')
TokenInfo(type=1 (NAME), string='if', start=(37, 16), end=(37, 18), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(37, 19), end=(37, 22), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string='[', start=(37, 22), end=(37, 23), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=1 (NAME), string='i', start=(37, 23), end=(37, 24), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string=']', start=(37, 24), end=(37, 25), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string='<', start=(37, 26), end=(37, 27), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(37, 28), end=(37, 31), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string='[', start=(37, 31), end=(37, 32), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=1 (NAME), string='j', start=(37, 32), end=(37, 33), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string=']', start=(37, 33), end=(37, 34), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=54 (OP), string='{', start=(37, 35), end=(37, 36), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(37, 36), end=(37, 38), line='                if arr[i] < arr[j] {\r\n')
TokenInfo(type=1 (NAME), string='new_arr', start=(38, 20), end=(38, 27), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='.', start=(38, 27), end=(38, 28), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='push', start=(38, 28), end=(38, 32), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='(', start=(38, 32), end=(38, 33), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(38, 33), end=(38, 36), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='[', start=(38, 36), end=(38, 37), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='i', start=(38, 37), end=(38, 38), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string=']', start=(38, 38), end=(38, 39), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string=')', start=(38, 39), end=(38, 40), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(38, 40), end=(38, 42), line='                    new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='i', start=(39, 20), end=(39, 21), line='                    i = i + 1\r\n')
TokenInfo(type=54 (OP), string='=', start=(39, 22), end=(39, 23), line='                    i = i + 1\r\n')
TokenInfo(type=1 (NAME), string='i', start=(39, 24), end=(39, 25), line='                    i = i + 1\r\n')
TokenInfo(type=54 (OP), string='+', start=(39, 26), end=(39, 27), line='                    i = i + 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(39, 28), end=(39, 29), line='                    i = i + 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(39, 29), end=(39, 31), line='                    i = i + 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(40, 16), end=(40, 17), line='                } else {\r\n')
TokenInfo(type=1 (NAME), string='else', start=(40, 18), end=(40, 22), line='                } else {\r\n')
TokenInfo(type=54 (OP), string='{', start=(40, 23), end=(40, 24), line='                } else {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(40, 24), end=(40, 26), line='                } else {\r\n')
TokenInfo(type=1 (NAME), string='new_arr', start=(41, 20), end=(41, 27), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='.', start=(41, 27), end=(41, 28), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='push', start=(41, 28), end=(41, 32), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='(', start=(41, 32), end=(41, 33), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(41, 33), end=(41, 36), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='[', start=(41, 36), end=(41, 37), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='j', start=(41, 37), end=(41, 38), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string=']', start=(41, 38), end=(41, 39), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string=')', start=(41, 39), end=(41, 40), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(41, 40), end=(41, 42), line='                    new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='j', start=(42, 20), end=(42, 21), line='                    j = j + 1\r\n')
TokenInfo(type=54 (OP), string='=', start=(42, 22), end=(42, 23), line='                    j = j + 1\r\n')
TokenInfo(type=1 (NAME), string='j', start=(42, 24), end=(42, 25), line='                    j = j + 1\r\n')
TokenInfo(type=54 (OP), string='+', start=(42, 26), end=(42, 27), line='                    j = j + 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(42, 28), end=(42, 29), line='                    j = j + 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(42, 29), end=(42, 31), line='                    j = j + 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(43, 16), end=(43, 17), line='                }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(43, 17), end=(43, 19), line='                }\r\n')
TokenInfo(type=54 (OP), string='}', start=(44, 12), end=(44, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(44, 13), end=(44, 15), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(45, 0), end=(45, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='while', start=(46, 12), end=(46, 17), line='            while i <= mid {\r\n')
TokenInfo(type=1 (NAME), string='i', start=(46, 18), end=(46, 19), line='            while i <= mid {\r\n')
TokenInfo(type=54 (OP), string='<=', start=(46, 20), end=(46, 22), line='            while i <= mid {\r\n')
TokenInfo(type=1 (NAME), string='mid', start=(46, 23), end=(46, 26), line='            while i <= mid {\r\n')
TokenInfo(type=54 (OP), string='{', start=(46, 27), end=(46, 28), line='            while i <= mid {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(46, 28), end=(46, 30), line='            while i <= mid {\r\n')
TokenInfo(type=1 (NAME), string='new_arr', start=(47, 16), end=(47, 23), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='.', start=(47, 23), end=(47, 24), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='push', start=(47, 24), end=(47, 28), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='(', start=(47, 28), end=(47, 29), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(47, 29), end=(47, 32), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string='[', start=(47, 32), end=(47, 33), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='i', start=(47, 33), end=(47, 34), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string=']', start=(47, 34), end=(47, 35), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=54 (OP), string=')', start=(47, 35), end=(47, 36), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(47, 36), end=(47, 38), line='                new_arr.push(arr[i])\r\n')
TokenInfo(type=1 (NAME), string='i', start=(48, 16), end=(48, 17), line='                i = i + 1\r\n')
TokenInfo(type=54 (OP), string='=', start=(48, 18), end=(48, 19), line='                i = i + 1\r\n')
TokenInfo(type=1 (NAME), string='i', start=(48, 20), end=(48, 21), line='                i = i + 1\r\n')
TokenInfo(type=54 (OP), string='+', start=(48, 22), end=(48, 23), line='                i = i + 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(48, 24), end=(48, 25), line='                i = i + 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(48, 25), end=(48, 27), line='                i = i + 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(49, 12), end=(49, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(49, 13), end=(49, 15), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(50, 0), end=(50, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='while', start=(51, 12), end=(51, 17), line='            while j <= end {\r\n')
TokenInfo(type=1 (NAME), string='j', start=(51, 18), end=(51, 19), line='            while j <= end {\r\n')
TokenInfo(type=54 (OP), string='<=', start=(51, 20), end=(51, 22), line='            while j <= end {\r\n')
TokenInfo(type=1 (NAME), string='end', start=(51, 23), end=(51, 26), line='            while j <= end {\r\n')
TokenInfo(type=54 (OP), string='{', start=(51, 27), end=(51, 28), line='            while j <= end {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(51, 28), end=(51, 30), line='            while j <= end {\r\n')
TokenInfo(type=1 (NAME), string='new_arr', start=(52, 16), end=(52, 23), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='.', start=(52, 23), end=(52, 24), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='push', start=(52, 24), end=(52, 28), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='(', start=(52, 28), end=(52, 29), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='arr', start=(52, 29), end=(52, 32), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string='[', start=(52, 32), end=(52, 33), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='j', start=(52, 33), end=(52, 34), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string=']', start=(52, 34), end=(52, 35), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=54 (OP), string=')', start=(52, 35), end=(52, 36), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(52, 36), end=(52, 38), line='                new_arr.push(arr[j])\r\n')
TokenInfo(type=1 (NAME), string='j', start=(53, 16), end=(53, 17), line='                j = j + 1\r\n')
TokenInfo(type=54 (OP), string='=', start=(53, 18), end=(53, 19), line='                j = j + 1\r\n')
TokenInfo(type=1 (NAME), string='j', start=(53, 20), end=(53, 21), line='                j = j + 1\r\n')
TokenInfo(type=54 (OP), string='+', start=(53, 22), end=(53, 23), line='                j = j + 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(53, 24), end=(53, 25), line='                j = j + 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(53, 25), end=(53, 27), line='                j = j + 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(54, 12), end=(54, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(54, 13), end=(54, 15), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(55, 0), end=(55, 2), line='\r\n')
TokenInfo(type=54 (OP), string='}', start=(56, 8), end=(56, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(56, 9), end=(56, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(57, 4), end=(57, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(57, 5), end=(57, 7), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(58, 0), end=(58, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='some', start=(59, 4), end=(59, 8), line='    some() {\r\n')
TokenInfo(type=54 (OP), string='(', start=(59, 8), end=(59, 9), line='    some() {\r\n')
TokenInfo(type=54 (OP), string=')', start=(59, 9), end=(59, 10), line='    some() {\r\n')
TokenInfo(type=54 (OP), string='{', start=(59, 11), end=(59, 12), line='    some() {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(59, 12), end=(59, 14), line='    some() {\r\n')
TokenInfo(type=1 (NAME), string='if', start=(60, 8), end=(60, 10), line='        if 92 > 14523 {\r\n')
TokenInfo(type=2 (NUMBER), string='92', start=(60, 11), end=(60, 13), line='        if 92 > 14523 {\r\n')
TokenInfo(type=54 (OP), string='>', start=(60, 14), end=(60, 15), line='        if 92 > 14523 {\r\n')
TokenInfo(type=2 (NUMBER), string='14523', start=(60, 16), end=(60, 21), line='        if 92 > 14523 {\r\n')
TokenInfo(type=54 (OP), string='{', start=(60, 22), end=(60, 23), line='        if 92 > 14523 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(60, 23), end=(60, 25), line='        if 92 > 14523 {\r\n')
TokenInfo(type=1 (NAME), string='while', start=(61, 11), end=(61, 16), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(61, 17), end=(61, 18), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=1 (NAME), string='fnjmkjdsl', start=(61, 18), end=(61, 27), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(61, 27), end=(61, 28), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(61, 29), end=(61, 30), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(61, 30), end=(61, 32), line='           while (fnjmkjdsl) {\r\n')
TokenInfo(type=1 (NAME), string='loop', start=(62, 16), end=(62, 20), line='                loop {\r\n')
TokenInfo(type=54 (OP), string='{', start=(62, 21), end=(62, 22), line='                loop {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(62, 22), end=(62, 24), line='                loop {\r\n')
TokenInfo(type=1 (NAME), string='a', start=(63, 20), end=(63, 21), line='                    a = 5 + 4\r\n')
TokenInfo(type=54 (OP), string='=', start=(63, 22), end=(63, 23), line='                    a = 5 + 4\r\n')
TokenInfo(type=2 (NUMBER), string='5', start=(63, 24), end=(63, 25), line='                    a = 5 + 4\r\n')
TokenInfo(type=54 (OP), string='+', start=(63, 26), end=(63, 27), line='                    a = 5 + 4\r\n')
TokenInfo(type=2 (NUMBER), string='4', start=(63, 28), end=(63, 29), line='                    a = 5 + 4\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(63, 29), end=(63, 31), line='                    a = 5 + 4\r\n')
TokenInfo(type=54 (OP), string='}', start=(64, 16), end=(64, 17), line='                }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(64, 17), end=(64, 19), line='                }\r\n')
TokenInfo(type=54 (OP), string='}', start=(65, 11), end=(65, 12), line='           }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(65, 12), end=(65, 14), line='           }\r\n')
TokenInfo(type=54 (OP), string='}', start=(66, 8), end=(66, 9), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='else', start=(66, 10), end=(66, 14), line='        } else {\r\n')
TokenInfo(type=54 (OP), string='{', start=(66, 15), end=(66, 16), line='        } else {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(66, 16), end=(66, 18), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(67, 11), end=(67, 17), line='           return 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(67, 18), end=(67, 19), line='           return 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(67, 19), end=(67, 21), line='           return 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(68, 8), end=(68, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(68, 9), end=(68, 11), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(69, 0), end=(69, 2), line='\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(70, 0), end=(70, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='while', start=(71, 8), end=(71, 13), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=1 (NAME), string='true', start=(71, 14), end=(71, 18), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=54 (OP), string='+', start=(71, 19), end=(71, 20), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=2 (NUMBER), string='4', start=(71, 21), end=(71, 22), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=54 (OP), string='==', start=(71, 23), end=(71, 25), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=2 (NUMBER), string='3', start=(71, 26), end=(71, 27), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=54 (OP), string='{', start=(71, 28), end=(71, 29), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(71, 29), end=(71, 31), line='        while true + 4 == 3 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(72, 12), end=(72, 14), line='            \r\n')
TokenInfo(type=54 (OP), string='}', start=(73, 8), end=(73, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(73, 9), end=(73, 11), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(74, 0), end=(74, 2), line='\r\n')
TokenInfo(type=54 (OP), string='}', start=(75, 4), end=(75, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(75, 5), end=(75, 7), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(76, 0), end=(76, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='toString', start=(77, 4), end=(77, 12), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(77, 12), end=(77, 13), line='    toString(digit) {\r\n')
TokenInfo(type=1 (NAME), string='digit', start=(77, 13), end=(77, 18), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(77, 18), end=(77, 19), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(77, 20), end=(77, 21), line='    toString(digit) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(77, 21), end=(77, 23), line='    toString(digit) {\r\n')
TokenInfo(type=1 (NAME), string='switch', start=(78, 8), end=(78, 14), line='        switch digit {\r\n')
TokenInfo(type=1 (NAME), string='digit', start=(78, 15), end=(78, 20), line='        switch digit {\r\n')
TokenInfo(type=54 (OP), string='{', start=(78, 21), end=(78, 22), line='        switch digit {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(78, 22), end=(78, 24), line='        switch digit {\r\n')
TokenInfo(type=2 (NUMBER), string='0', start=(79, 12), end=(79, 13), line='            0: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(79, 13), end=(79, 14), line='            0: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(79, 15), end=(79, 16), line='            0: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(79, 17), end=(79, 19), line='            0: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(80, 16), end=(80, 22), line='                return "0"\r\n')
TokenInfo(type=3 (STRING), string='"0"', start=(80, 23), end=(80, 26), line='                return "0"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(80, 26), end=(80, 28), line='                return "0"\r\n')
TokenInfo(type=54 (OP), string='}', start=(81, 12), end=(81, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(81, 13), end=(81, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(82, 12), end=(82, 13), line='            1: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(82, 13), end=(82, 14), line='            1: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(82, 15), end=(82, 16), line='            1: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(82, 17), end=(82, 19), line='            1: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(83, 16), end=(83, 22), line='                return "1"\r\n')
TokenInfo(type=3 (STRING), string='"1"', start=(83, 23), end=(83, 26), line='                return "1"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(83, 26), end=(83, 28), line='                return "1"\r\n')
TokenInfo(type=54 (OP), string='}', start=(84, 12), end=(84, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(84, 13), end=(84, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='2', start=(85, 12), end=(85, 13), line='            2: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(85, 13), end=(85, 14), line='            2: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(85, 15), end=(85, 16), line='            2: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(85, 17), end=(85, 19), line='            2: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(86, 15), end=(86, 21), line='               return "2"\r\n')
TokenInfo(type=3 (STRING), string='"2"', start=(86, 22), end=(86, 25), line='               return "2"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(86, 25), end=(86, 27), line='               return "2"\r\n')
TokenInfo(type=54 (OP), string='}', start=(87, 12), end=(87, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(87, 13), end=(87, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='3', start=(88, 12), end=(88, 13), line='            3: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(88, 13), end=(88, 14), line='            3: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(88, 15), end=(88, 16), line='            3: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(88, 17), end=(88, 19), line='            3: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(89, 16), end=(89, 22), line='                return "3"\r\n')
TokenInfo(type=3 (STRING), string='"3"', start=(89, 23), end=(89, 26), line='                return "3"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(89, 26), end=(89, 28), line='                return "3"\r\n')
TokenInfo(type=54 (OP), string='}', start=(90, 12), end=(90, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(90, 13), end=(90, 15), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(91, 12), end=(91, 14), line='            \r\n')
TokenInfo(type=54 (OP), string='}', start=(92, 8), end=(92, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(92, 9), end=(92, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(93, 4), end=(93, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(93, 5), end=(93, 7), line='    }\r\n')
TokenInfo(type=54 (OP), string='}', start=(94, 0), end=(94, 1), line='}\r\n')
TokenInfo(type=4 (NEWLINE), string='\r\n', start=(94, 1), end=(94, 3), line='}\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(95, 0), end=(95, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='global', start=(96, 0), end=(96, 6), line='global {\r\n')
TokenInfo(type=54 (OP), string='{', start=(96, 7), end=(96, 8), line='global {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(96, 8), end=(96, 10), line='global {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(97, 0), end=(97, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='factorial', start=(98, 4), end=(98, 13), line='    factorial(n) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(98, 13), end=(98, 14), line='    factorial(n) {\r\n')
TokenInfo(type=1 (NAME), string='n', start=(98, 14), end=(98, 15), line='    factorial(n) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(98, 15), end=(98, 16), line='    factorial(n) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(98, 17), end=(98, 18), line='    factorial(n) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(98, 18), end=(98, 20), line='    factorial(n) {\r\n')
TokenInfo(type=1 (NAME), string='if', start=(99, 8), end=(99, 10), line='        if n == 0 {\r\n')
TokenInfo(type=1 (NAME), string='n', start=(99, 11), end=(99, 12), line='        if n == 0 {\r\n')
TokenInfo(type=54 (OP), string='==', start=(99, 13), end=(99, 15), line='        if n == 0 {\r\n')
TokenInfo(type=2 (NUMBER), string='0', start=(99, 16), end=(99, 17), line='        if n == 0 {\r\n')
TokenInfo(type=54 (OP), string='{', start=(99, 18), end=(99, 19), line='        if n == 0 {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(99, 19), end=(99, 21), line='        if n == 0 {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(100, 12), end=(100, 18), line='            return 1\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(100, 19), end=(100, 20), line='            return 1\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(100, 20), end=(100, 22), line='            return 1\r\n')
TokenInfo(type=54 (OP), string='}', start=(101, 8), end=(101, 9), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='else', start=(101, 10), end=(101, 14), line='        } else {\r\n')
TokenInfo(type=54 (OP), string='{', start=(101, 15), end=(101, 16), line='        } else {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(101, 16), end=(101, 18), line='        } else {\r\n')
TokenInfo(type=1 (NAME), string='return', start=(102, 12), end=(102, 18), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=1 (NAME), string='n', start=(102, 19), end=(102, 20), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=54 (OP), string='*', start=(102, 21), end=(102, 22), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=1 (NAME), string='factorial', start=(102, 23), end=(102, 32), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=54 (OP), string='(', start=(102, 32), end=(102, 33), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=1 (NAME), string='n', start=(102, 33), end=(102, 34), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=54 (OP), string='-', start=(102, 35), end=(102, 36), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(102, 37), end=(102, 38), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=54 (OP), string=')', start=(102, 38), end=(102, 39), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(102, 39), end=(102, 41), line='            return n * factorial(n - 1)\r\n')
TokenInfo(type=54 (OP), string='}', start=(103, 8), end=(103, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(103, 9), end=(103, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(104, 4), end=(104, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(104, 5), end=(104, 7), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(105, 0), end=(105, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='something2', start=(106, 4), end=(106, 14), line='    something2() {\r\n')
TokenInfo(type=54 (OP), string='(', start=(106, 14), end=(106, 15), line='    something2() {\r\n')
TokenInfo(type=54 (OP), string=')', start=(106, 15), end=(106, 16), line='    something2() {\r\n')
TokenInfo(type=54 (OP), string='{', start=(106, 17), end=(106, 18), line='    something2() {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(106, 18), end=(106, 20), line='    something2() {\r\n')
TokenInfo(type=1 (NAME), string='loop', start=(107, 8), end=(107, 12), line='        loop {\r\n')
TokenInfo(type=54 (OP), string='{', start=(107, 13), end=(107, 14), line='        loop {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(107, 14), end=(107, 16), line='        loop {\r\n')
TokenInfo(type=61 (COMMENT), string='# fds', start=(108, 12), end=(108, 17), line='            # fds\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(108, 17), end=(108, 19), line='            # fds\r\n')
TokenInfo(type=54 (OP), string='}', start=(109, 8), end=(109, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(109, 9), end=(109, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(110, 4), end=(110, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(110, 5), end=(110, 7), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(111, 0), end=(111, 2), line='\r\n')
TokenInfo(type=1 (NAME), string='main', start=(112, 4), end=(112, 8), line='    main(args) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(112, 8), end=(112, 9), line='    main(args) {\r\n')
TokenInfo(type=1 (NAME), string='args', start=(112, 9), end=(112, 13), line='    main(args) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(112, 13), end=(112, 14), line='    main(args) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(112, 15), end=(112, 16), line='    main(args) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(112, 16), end=(112, 18), line='    main(args) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(113, 0), end=(113, 2), line='\r\n')
TokenInfo(type=61 (COMMENT), string='# stdio.printf("Hello World!\\n")', start=(114, 8), end=(114, 40), line='        # stdio.printf("Hello World!\\n")\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(114, 40), end=(114, 42), line='        # stdio.printf("Hello World!\\n")\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(115, 0), end=(115, 2), line='\r\n')
TokenInfo(type=54 (OP), string='}', start=(116, 4), end=(116, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(116, 5), end=(116, 7), line='    }\r\n')
TokenInfo(type=54 (OP), string='}', start=(117, 0), end=(117, 1), line='}\r\n')
TokenInfo(type=4 (NEWLINE), string='\r\n', start=(117, 1), end=(117, 3), line='}\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(118, 0), end=(118, 2), line='\r\n')
TokenInfo(type=0 (ENDMARKER), string='', start=(119, 0), end=(119, 0), line='')
