TokenInfo(type=63 (ENCODING), string='utf-8', start=(0, 0), end=(0, 0), line='')
TokenInfo(type=1 (NAME), string='global', start=(1, 0), end=(1, 6), line='global {\r\n')
TokenInfo(type=54 (OP), string='{', start=(1, 7), end=(1, 8), line='global {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(1, 8), end=(1, 10), line='global {\r\n')
TokenInfo(type=1 (NAME), string='toString', start=(2, 4), end=(2, 12), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string='(', start=(2, 12), end=(2, 13), line='    toString(digit) {\r\n')
TokenInfo(type=1 (NAME), string='digit', start=(2, 13), end=(2, 18), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string=')', start=(2, 18), end=(2, 19), line='    toString(digit) {\r\n')
TokenInfo(type=54 (OP), string='{', start=(2, 20), end=(2, 21), line='    toString(digit) {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(2, 21), end=(2, 23), line='    toString(digit) {\r\n')
TokenInfo(type=1 (NAME), string='switch', start=(3, 8), end=(3, 14), line='        switch digit {\r\n')
TokenInfo(type=1 (NAME), string='digit', start=(3, 15), end=(3, 20), line='        switch digit {\r\n')
TokenInfo(type=54 (OP), string='{', start=(3, 21), end=(3, 22), line='        switch digit {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(3, 22), end=(3, 24), line='        switch digit {\r\n')
TokenInfo(type=2 (NUMBER), string='0', start=(4, 12), end=(4, 13), line='            0: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(4, 13), end=(4, 14), line='            0: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(4, 15), end=(4, 16), line='            0: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(4, 17), end=(4, 19), line='            0: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(5, 16), end=(5, 22), line='                return "0"\r\n')
TokenInfo(type=3 (STRING), string='"0"', start=(5, 23), end=(5, 26), line='                return "0"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(5, 26), end=(5, 28), line='                return "0"\r\n')
TokenInfo(type=54 (OP), string='}', start=(6, 12), end=(6, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(6, 13), end=(6, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='1', start=(7, 12), end=(7, 13), line='            1: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(7, 13), end=(7, 14), line='            1: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(7, 15), end=(7, 16), line='            1: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(7, 17), end=(7, 19), line='            1: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(8, 16), end=(8, 22), line='                return "1"\r\n')
TokenInfo(type=3 (STRING), string='"1"', start=(8, 23), end=(8, 26), line='                return "1"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(8, 26), end=(8, 28), line='                return "1"\r\n')
TokenInfo(type=54 (OP), string='}', start=(9, 12), end=(9, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(9, 13), end=(9, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='2', start=(10, 12), end=(10, 13), line='            2: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(10, 13), end=(10, 14), line='            2: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(10, 15), end=(10, 16), line='            2: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(10, 17), end=(10, 19), line='            2: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(11, 15), end=(11, 21), line='               return "2"\r\n')
TokenInfo(type=3 (STRING), string='"2"', start=(11, 22), end=(11, 25), line='               return "2"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(11, 25), end=(11, 27), line='               return "2"\r\n')
TokenInfo(type=54 (OP), string='}', start=(12, 12), end=(12, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(12, 13), end=(12, 15), line='            }\r\n')
TokenInfo(type=2 (NUMBER), string='3', start=(13, 12), end=(13, 13), line='            3: { \r\n')
TokenInfo(type=54 (OP), string=':', start=(13, 13), end=(13, 14), line='            3: { \r\n')
TokenInfo(type=54 (OP), string='{', start=(13, 15), end=(13, 16), line='            3: { \r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(13, 17), end=(13, 19), line='            3: { \r\n')
TokenInfo(type=1 (NAME), string='return', start=(14, 16), end=(14, 22), line='                return "3"\r\n')
TokenInfo(type=3 (STRING), string='"3"', start=(14, 23), end=(14, 26), line='                return "3"\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(14, 26), end=(14, 28), line='                return "3"\r\n')
TokenInfo(type=54 (OP), string='}', start=(15, 12), end=(15, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(15, 13), end=(15, 15), line='            }\r\n')
TokenInfo(type=1 (NAME), string='sad', start=(16, 12), end=(16, 15), line='            sad : {\r\n')
TokenInfo(type=54 (OP), string=':', start=(16, 16), end=(16, 17), line='            sad : {\r\n')
TokenInfo(type=54 (OP), string='{', start=(16, 18), end=(16, 19), line='            sad : {\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(16, 19), end=(16, 21), line='            sad : {\r\n')
TokenInfo(type=1 (NAME), string='asdsa', start=(17, 16), end=(17, 21), line='                asdsa\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(17, 21), end=(17, 23), line='                asdsa\r\n')
TokenInfo(type=54 (OP), string='}', start=(18, 12), end=(18, 13), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(18, 13), end=(18, 15), line='            }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(19, 12), end=(19, 14), line='            \r\n')
TokenInfo(type=54 (OP), string='}', start=(20, 8), end=(20, 9), line='        }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(20, 9), end=(20, 11), line='        }\r\n')
TokenInfo(type=54 (OP), string='}', start=(21, 4), end=(21, 5), line='    }\r\n')
TokenInfo(type=62 (NL), string='\r\n', start=(21, 5), end=(21, 7), line='    }\r\n')
TokenInfo(type=54 (OP), string='}', start=(22, 0), end=(22, 1), line='}')
TokenInfo(type=4 (NEWLINE), string='', start=(22, 1), end=(22, 2), line='')
TokenInfo(type=0 (ENDMARKER), string='', start=(23, 0), end=(23, 0), line='')
